<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>approve low risk</name>
  <uuid>80213c63-0e58-41ac-a110-20500c55cf6f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    'the risk' is Low
then
    set decision to true ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
