<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>reject high risk</name>
  <uuid>5aee0643-dfc2-49bf-b3aa-cd6e0566f80e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    'the risk' is High
then
    set decision to false ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
